apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlfrontenddeployment
  namespace: urlshortenerapp
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-pod
          image: salaheddine122/frontend
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: urlfrontendservice
  namespace: urlshortenerapp
  labels:
    app: frontend
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend
