apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlbackenddeployment
  namespace: urlshortenerapp
  labels:
    environement: prod
spec:
  selector:
    matchLabels:
      app: urlbackend
  replicas: 2 
  template:
    metadata:
      labels:
        app: urlbackend
    spec:
      imagePullSecrets:
      - name: dockersecret
      containers:
      - name: urlbackend
        image: salaheddine122/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi" 
            cpu: "250m"     
          limits:
            memory: "256Mi" 
            cpu: "500m"
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: urlbackendconfigmap
              key: PORT
        - name: DOMAIN
          valueFrom:
            configMapKeyRef:
              name: urlbackendconfigmap
              key: DOMAIN
        - name: PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: urlbackendconfigmap
              key: PROTOCOL
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: urlbackendconfigmap
              key: DATABASE_URL

---
apiVersion: v1
kind: Service
metadata:
  name: urlbackendservice
  namespace: urlshortenerapp
  labels:
    app: urlbackend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: urlbackend

